### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [envirosolutionspl/uldk#1]
# Problem

Can you please add a working link for the plugin home page.

Also add a little description in English of what the plugin does

cc @envirosolutionspl

**Comment by envirosolutionspl** [comment]
> # Problem
> Can you please add a working link for the plugin home page.
> 
> Also add a little description in English of what the plugin does
> 
> cc @envirosolutionspl

@NyakudyaA  Description added. There is no plugin home page yet. It has been changed to github repository.
