### ISSUE TITLE
Problem z wtyczką Usługa Lokalizacji Działek Katastralnych

### ISSUE THREAD

**Issue by bnochowicz** [envirosolutionspl/uldk#10]
Dzień dobry,
 
Chciałem skorzystać z Państwa bezpłatnej wtyczki "Usługa Lokalizacji Działek Katastralnych", niestety wyskakuje mi błąd.
Sprawdzałem na 3 wersjach QGIS: 3.16, 3.22 oraz najnowszej, 3.28.
Korzystam z Macbook, obecna wersja systemu 13.0, na poprzedniej 12.6 wyskakiwały również te same błędy.
Załączam logi, które pokazują się na starcie aplikacji.
 
Jeżeli są Państwo w stanie nakierować mnie, w jaki sposób naprawić wyskakujące błędy, tak żeby wszystko działało, to będę bardzo wdzięczny.

Nie można wczytać wtyczki 'uldk_gugik' z powodu błędu wywołania jej metody classFactory()

LookupError: unknown encoding: ANSI
Traceback (most recent call last):
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/bartosz/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/uldk_gugik/__init__.py", line 36, in classFactory
    return UldkGugik(iface)
  File "/Users/bartosz/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/uldk_gugik/uldk_gugik.py", line 100, in __init__
    self.dlg = UldkGugikDialog()
  File "/Users/bartosz/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/uldk_gugik/uldk_gugik_dialog.py", line 58, in __init__
    self.regionFetch = RegionFetch()
  File "/Users/bartosz/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/uldk_gugik/uldk.py", line 8, in __init__
    self.obrebDict = self.__fetchObrebDict()
  File "/Users/bartosz/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/uldk_gugik/uldk.py", line 22, in __fetchObrebDict
    resp=RegionFetch.openObrebList(self)
  File "/Users/bartosz/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/uldk_gugik/uldk.py", line 14, in openObrebList
    with open(os.path.join(os.path.dirname(__file__),'obreby.csv'), encoding="ANSI") as f:
LookupError: unknown encoding: ANSI
 

 
Wersja Pythona: 3.9.5 (default, Sep 10 2021, 16:18:19) [Clang 12.0.5 (clang-1205.0.22.11)]
Wersja QGIS: 3.28.1-Firenze Firenze, fde3b8fbb8

Lokalizacja Pythona:
/Applications/QGIS.app/Contents/MacOS/../Resources/python
/Users/bartosz/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/bartosz/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/Fiona-1.8.13.post1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/matplotlib-3.3.0-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/scipy-1.5.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/opencv_contrib_python-4.3.0.36-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/lib-dynload
/Applications/QGIS.app/Contents/MacOS/lib/python3.9
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages
/Applications/QGIS.app/Contents/MacOS/lib/python39.zip
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/geopandas-0.8.1-py3.9.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/patsy-0.5.1-py3.9.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/statsmodels-0.11.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/Pillow-7.2.0-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/netCDF4-1.5.4-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numpy-1.20.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/rasterio-1.1.5-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/pandas-1.3.3-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/cftime-1.2.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/pyproj-3.2.0-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/Rtree-0.9.7-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/GDAL-3.3.2-py3.9-macosx-10.13.0-x86_64.egg
/Users/bartosz/Library/Application Support/QGIS/QGIS3/profiles/default/python

**Comment by kacpertarka** [comment]
Błąd poprawiony

**Comment by wojtek19022** [comment]
Wtyczka nie korzysta już z pliku powodującego błąd

**Comment by wojtek19022** [comment]
@bnochowicz pod poniższym linkiem znajduje się najnowsza wersja wtyczki:
https://github.com/envirosolutionspl/uldk/tree/development
