### ISSUE TITLE
Pobieranie przez nazwę obrębu i nr działki

### ISSUE THREAD

**Issue by wojtek19022** [envirosolutionspl/uldk#11]
/Kiedy użytkownik chce wczytać obręb, którego ma tyczyć działka, nie są podczytywane obręby. Dotyczy to zakładki wybór przez nazwę obrębu i nr działki.
![image](https://github.com/envirosolutionspl/uldk/assets/113895660/8564f5d6-5761-47b7-b477-0709746d89c2)

**Comment by wojtek19022** [comment]
@kacpertarka lepiej działa pobieranie działek, ale w komunikacie końcowym lepiej jest napisać pobrano działkę o nr tym i tym albo o terycie tym i tym, a nie zawierając tylko informację "pobrano obrys obiekty [obręb] [nr działki]".

**Comment by wojtek19022** [comment]
@kacpertarka działki nie pobierają się prawidłowo. Przykładowo zaznaczyłem takie opcje jak poniżej i otrzymałem działkę zamiast w województwie kujawsko-pomorskim, to w mazowieckim:
![image](https://github.com/envirosolutionspl/uldk/assets/113895660/d0bd5c7b-e9f3-4aa2-b873-e7b4b9c27e27)

**Comment by kacpertarka** [comment]
@wojtek19022

**Comment by kacpertarka** [comment]
@wojtek19022

**Comment by wojtek19022** [comment]
Błąd poprawiony, działki pobierają się zarówno dla mniejszych jak i większych miejscowości na terenie Polski
