### ISSUE TITLE
wtyczka się długo ładuje

### ISSUE THREAD

**Issue by envirosolutionspl** [envirosolutionspl/uldk#13]
![image](https://github.com/envirosolutionspl/uldk/assets/25906739/1982c2f9-b77f-46ee-b5a0-e91a43db31c2)
przy uruchamianiu QGIS ponad 10 sekund trwa ładowanie wtyczki. QGIS 3.32

**Comment by kacpertarka** [comment]
Problem z długością ładowania wtyczki poprawiony @envirosolutionspl
