### ISSUE TITLE
Zapytania do serwera ULDK

### ISSUE THREAD

**Issue by wojtek19022** [envirosolutionspl/uldk#15]
Zmiana zapytań do ULDK, żeby nie były tworzone z pomocą biblioteki requests, tylko QNetworkRequest

**Comment by kacpertarka** [comment]
Klasa Request odpowiedzialna za obsługę zapytań przy pomocy QNetworkRequest @wojtek19022

**Comment by wojtek19022** [comment]
Została zmieniona używana biblioteka z requests na QNetworkRequest
