### ISSUE TITLE
błędna lokalizacja działek po pobraniu przez wskazanie na mapie

### ISSUE THREAD

**Issue by envirosolutionspl** [envirosolutionspl/uldk#16]
QGIS 3.32, układ 3857, windows 11
Jak odtworzyć:
1. pobieramy dowolną działkę metodą wyboru z listy "wybór przez nazwę obrębu i numeru działki"
2. pobieramy działkę przez wskazanie na mapie (np. ALT + D)

Działka się pobiera, natomiast wyświetla się na oceanie. Prawdopodobnie obiekt działki wczytywany jest w złym układzie współrzędnych i brakuje transformacji.

![image](https://github.com/envirosolutionspl/uldk/assets/25906739/481f80cf-a82c-4ceb-95ff-3ee6ca57d04e)

**Comment by kacpertarka** [comment]
Błąd poprawiony @envirosolutionspl

**Comment by wojtek19022** [comment]
Tworzy się warstwa tymczasowa z działkami wyselekcjonowanymi w tym samym układzie co układ projektu. Wyniki zgodne, atrybuty dobrze się przepisują.
