### ISSUE TITLE
Pobieranie przez XY

### ISSUE THREAD

**Issue by wojtek19022** [envirosolutionspl/uldk#18]
Podczas pobierania za pomocą X i Y wpisanego przez uzytkownika działka została zwrócona, ale z odwrotną osią X i Y. Poniżej przykład:
![image](https://github.com/envirosolutionspl/uldk/assets/113895660/d0ba6f68-0bcd-41fa-a805-fd32fe1ea303)

Na dolnym pasku zapisane współrzędne w układzie PL-1992, a w oknie zapisane te same współrzędne, tylko na odwrót i działka dopiero została zwrócona w dobrym miejscu.

**Comment by kacpertarka** [comment]
@wojtek19022

**Comment by wojtek19022** [comment]
Błąd załatany
