### ISSUE TITLE
Please change bugtracker link

### ISSUE THREAD

**Issue by pcav** [envirosolutionspl/uldk#2]
It currently points to the repo, not to the issues page.
Thanks.

**Comment by koallcia** [comment]
> It currently points to the repo, not to the issues page.
> Thanks.

Bugtracker link has changed.

**Comment by pcav** [comment]
not in http://plugins.qgis.org/plugins/uldk_gugik/
cheers

**Comment by envirosolutionspl** [comment]
> not in http://plugins.qgis.org/plugins/uldk_gugik/
> cheers

Changed, and added new enhanced version

**Comment by pcav** [comment]
It still ppoints to https://github.com/envirosolutionspl/uldk
cheers
