### ISSUE TITLE
Zmiana tekstu w zależności od zaznaczonej warstwy do pobrania

### ISSUE THREAD

**Issue by wojtek19022** [envirosolutionspl/uldk#20]
![image](https://github.com/envirosolutionspl/uldk/assets/113895660/ebb7cb9c-7937-4274-91f2-9a618f488f81)
Tekst powinien się zmieniać w zależności od zaznaczonej opcji, dla zaznaczonego województwa powinien się pojawić przykładowy identyfikator dla województwa, a nie dla województwa, obrębów itd.

**Comment by kacpertarka** [comment]
@wojtek19022

**Comment by wojtek19022** [comment]
Niewłaściwy opis w przypadku wyboru pobierania działek w panelu głównym odpowiadającym za pobieranie działek
![image](https://github.com/envirosolutionspl/uldk/assets/113895660/6b43f605-7faf-490c-acc6-d8501ed10e2f)
