### ISSUE TITLE
Pobieranie działki przez wybór z listy - pobierana działka ze złego obrębu

### ISSUE THREAD

**Issue by envirosolutionspl** [envirosolutionspl/uldk#25]
Zamiast działki z województwa pomorskiego - pobierana jest działka w województwie lubelskim
![image](https://github.com/envirosolutionspl/uldk/assets/25906739/4849fe48-dbca-44a0-a7cb-6a0f945f6165)

![image](https://github.com/envirosolutionspl/uldk/assets/25906739/d2aaed52-d04c-409c-b82b-fb89173296a0)

**Comment by wojtek19022** [comment]
Potrzebne jest dodanie opcji wybrania arkusza, tutaj potrzebne jest dopisanie AR_1 na początku.

**Comment by mxichuu** [comment]
W moim przypadku nie pokazują się działki na kilku różnych arkuszach. W przypadku działek o numerze 9 znajdujących się w Radomiu Śródmieście2 powinno podczas wyszukiwania dać możliwość wyboru w 3 różnych arkuszach, ale pokazuje się tylko w jednym. 
![image](https://github.com/envirosolutionspl/uldk/assets/147042353/8ce00446-3d60-41dd-80a9-ec76570e14be)

![image](https://github.com/envirosolutionspl/uldk/assets/147042353/ebe1636a-cc85-4dea-a59b-646d785c8914)

**Comment by wojtek19022** [comment]
@mxichuu najwidoczniej wszystkie elementy faktycznie się nie dodają. Załatam to w piątek

**Comment by wojtek19022** [comment]
W wersji 1.3.0 zostały wprowadzone zmiany
