### ISSUE TITLE
Nieintuicyjne zachowanie klawisza akcji wtyczki

### ISSUE THREAD

**Issue by envirosolutionspl** [envirosolutionspl/uldk#28]
Uruchomienie akcji wtyczki z paska narzędzi w momencie gdy okno wtyczki jest włączone, chowa okno wtyczki pod okno główne
![image](https://github.com/envirosolutionspl/uldk/assets/25906739/274eec2b-ad6b-4df1-b862-c65acfc04acb)
Klawisz akcji powinien przywoływać okno wtyczki, a nie je chować.

**Comment by mxichuu** [comment]
@wojtek19022 problem jeszcze nie został rozwiązany, prawda? Chyba, że ja źle zrozumiałem jego treść?..

**Comment by wojtek19022** [comment]
Nie powinien się już pojawić ten błąd, zastosowałem wcześniejszy fragment kodu (jaki był w wersji 1.2.5) i działa tak samo jak wczesniej. Jak zamkniesz i otworzysz QGIS to sprawdź, czy po kilknięciu na ikonę wtyczki i później wciśnięciu ALT+D okno się zamyka

**Comment by mxichuu** [comment]
Tak, okno się zamyka.

**Comment by wojtek19022** [comment]
@mxichuu nagraj proszę to jak się takie coś dzieje, bo nigdy się z tym nie spotkałem. Otworzę na razie ponownie problem.
