### ISSUE TITLE
Obsługa błędnych geometrii

### ISSUE THREAD

**Issue by envirosolutionspl** [envirosolutionspl/uldk#3]
W przypadku niektórych działek usługa ULDK zwraca obiekt bez geometrii. Tak jest np. w przypadku działki o numerze 247801_1.0012.AR_11.1345/84.
Obecnie wtyczka dodaje obiekt z zerową geometrią i centruje mapę do punktu (0,0).
Należy obsłużyć brak geometrii w zwracanej działce. Najlepiej komunikatem i uniemożliwić dodanie obiektu bez geometrii do warstwy wyjściowej.

**Comment by koallcia** [comment]
Obsłużono brak geometrii w zwracanej działce. Dodano komunikat - obiekt nie jest dodawany do warstwy wyjściowej.
