### ISSUE TITLE
Wtyczka ULDK

### ISSUE THREAD

**Issue by Magdalena625** [envirosolutionspl/uldk#7]
Mam pytanie czy można za jednym razem zciągnąć większą liczbę działek poprzez wskazanie na mapie? Na ten moment znalazłam tylko wskazanie punktowe co powoduje ze ściąga się jedna działka. Zciągnięcie więc kilkudziesięciu działek poprzez wskazanie na mapie jest nie lada zabawą.

**Comment by wojtek19022** [comment]
Na ten moment nie przewidywany jest następujący rozwój wtyczki, proponuję zastosowanie skrótu ALT + D, który umożliwia "wyklikiwanie" większej ilości działek bez konieczności interwencji w interfejsie

**Comment by wojtek19022** [comment]
@Magdalena625  pod poniższym linkiem znajduje się najnowsza wersja wtyczki:
https://github.com/envirosolutionspl/uldk/tree/development

Zapraszam do testów
