### ISSUE TITLE
Opcja wyboru działki ULDK

### ISSUE THREAD

**Issue by KubaaW** [envirosolutionspl/uldk#8]
Czy opcja wyboru poprzez nazwę obrębu lub numer działki powinna być nieaktywna? Jak ją odblokować? Sytuacja ta sama na wersji 3.16 oraz 3.22

**Comment by wojtek19022** [comment]
Opcja jest widoczna w przypadku pobierania działek. Nie wykryto takiej sytuacji przy działaniu obecnej wersji wtyczki

**Comment by wojtek19022** [comment]
@KubaaW  pod poniższym linkiem znajduje się najnowsza wersja wtyczki:
https://github.com/envirosolutionspl/uldk/tree/development

Zapraszam do testów
